title: Joni Halabi
production_url: http://www.jhalabi.com
twitter_username: jonihalabi

icons: '/assets/icons'
images: '/assets/images'

sass:
  sass_dir: '/assets/_sass'
  style: compressed

permalink: /blog/:title
